# Generated by Django 4.2.30 on 2026-09-09 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='meal_data',
            field=models.CharField(default='0000000000000000000000000000000', max_length=32),
        ),
        migrations.CreateModel(
            name='MealTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='SUCCESS', max_length=20)),
                ('terminal_id', models.CharField(default='VENDOR_TERMINAL_1', max_length=50)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='mess.student')),
            ],
        ),
    ]
